repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        exclude: ^(venv/|cache/|output/|tests/sketches/)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^(venv/|cache/|output/|tests/sketches/)

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^(venv/|cache/|output/|tests/sketches/)
        args: ['--max-line-length=88', '--select=E9,F63,F7,F82']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        exclude: ^(venv/|cache/|output/|tests/sketches/|tests/|templates/|sketches/)
        additional_dependencies: [types-aiofiles]
        args: [--ignore-missing-imports, --no-strict-optional]
